import {atom} from "jotai";

export const AvatarImagesAtom = atom<string[]>([
    "https://i.ibb.co/nq4rtQXR/1.png",
    "https://i.ibb.co/ZRRLwdft/2.png",
    "https://i.ibb.co/8g2gW1Nc/11.png",
    "https://i.ibb.co/tTHrzyMN/12.png",
    "https://i.ibb.co/zHBQFS5f/22.png",
    "https://i.ibb.co/bR1vYN71/23.png",
    "https://i.ibb.co/v25zxp0/32.png",
    "https://i.ibb.co/27nxw6nf/33.png",
    "https://i.ibb.co/jv4TjhG1/34.png",
    "https://i.ibb.co/bM3vqz53/43.png",
    "https://i.ibb.co/SD64Vc4C/45.png",
    "https://i.ibb.co/GQ1gSwfp/55.png",
    "https://i.ibb.co/20jxr2HF/56.png",
    "https://i.ibb.co/Q5hpDLK/65.png" ,
    "https://i.ibb.co/cc4k2HH7/67.png",
    "https://i.ibb.co/jkLHL6fZ/76.png",
    "https://i.ibb.co/Swhk6TF7/78.png",
    "https://i.ibb.co/N6TDFNhj/88.png",
    "https://i.ibb.co/CpwX3L08/89.png",
    "https://i.ibb.co/FqH0f8c3/99.png",
    "https://i.ibb.co/N2K03MhL/100.png",
    "https://i.ibb.co/tPCd405D/101.png",
    "https://i.ibb.co/PvybzRXn/111.png",
    "https://i.ibb.co/mCdHBkMJ/121.png",
    "https://i.ibb.co/6372D9y/122.png",
    "https://i.ibb.co/MkLXWQky/132.png",
    "https://i.ibb.co/0yJCMKRc/133.png",
    "https://i.ibb.co/8gS53vNy/143.png",
    "https://i.ibb.co/fVdwMkhW/144.png",
    "https://i.ibb.co/QjnhsmTp/154.png",
    "https://i.ibb.co/JRSyTVs1/155.png",
    "https://i.ibb.co/wNJ0WhS5/165.png",
    "https://i.ibb.co/pvwHXStz/166.png",
    "https://i.ibb.co/MDt4B3n9/167.png",
    "https://i.ibb.co/gZbRHpZ0/168.png",
    "https://i.ibb.co/W40HZ69k/169.png",
    "https://i.ibb.co/V0hZJSJ9/179.png",
    "https://i.ibb.co/8khQRd8/cat.png",
    "https://i.ibb.co/p6vnT3T3/p.png" ,
    "https://i.ibb.co/LDSzLDJ2/q.png",
]);